./ingest_to_graphdb_ner.sh: 2: ./ingest_to_graphdb_ner.sh: source: not found
python: can't open file './03_upload_graphdb.py': [Errno 2] No such file or directory
